sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 1234
  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    accessKeyId: LTAI5t7bgW8pv3YrMuBp63i7
    accessKeySecret: IfpV7Ms7jRt7K9Dyqz6sTUIkQrSlm0
    bucketName: cosh
spring:
  redis:
    host: 127.0.0.1
    port: 6379
    password: 4285
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 1
        time-between-eviction-runs: 10s
